[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[redirects]]
  from = "/tools"
  to = "/index.html#tools"
  status = 301

[[redirects]]
  from = "/legal"
  to = "/legal/index.html"
  status = 301
